name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  test:
    runs-on: ubuntu-latest

    permissions: read-all

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          lfs: true

      - name: Setup node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --ignore-scripts --pure-lockfile

      - name: Build
        run: npm run build --if-present
        env:
          CI: true

      - name: Test
        run: npm test
        env:
          CI: true
